/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.tecnm.cdmadero.formulaecuacion2dogrado;

import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Manzanares
 */
public class FormulaGeneralFrame extends javax.swing.JFrame {

    /**
     * Creates new form FormulaGeneralFrame
     */
    public FormulaGeneralFrame() {
        initComponents();
        this.setTitle("Solución de Ecuaciones de 2do. Grado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        conversiones = new javax.swing.ButtonGroup();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        lblC = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lblXInicial = new javax.swing.JLabel();
        txtXIncial = new javax.swing.JTextField();
        txtXFinal = new javax.swing.JTextField();
        lblXFinal = new javax.swing.JLabel();
        btnCalcularTabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtIncremento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblX1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblX2 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtA =  new javax.swing.JFormattedTextField(new Double(0.0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarAlBoton(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblA.setText("Coeficiente A:");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, -1));

        lblB.setText("Coeficiente B:");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, -1));
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 100, -1));

        lblC.setText("Coeficiente C:");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, -1));
        getContentPane().add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblXInicial.setText("x incial:");
        jPanel3.add(lblXInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel3.add(txtXIncial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, -1));
        jPanel3.add(txtXFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, -1));

        lblXFinal.setText("x final:");
        jPanel3.add(lblXFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnCalcularTabla.setText("Calcular");
        btnCalcularTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTablaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalcularTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        txtResultados.setEditable(false);
        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 90));

        jLabel1.setText("Incremento:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));
        jPanel3.add(txtIncremento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));

        jTabbedPane1.addTab("Tabla", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX1.setText("Raiz x1:");
        jPanel1.add(lblX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, -1));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lblX2.setText("Raiz x2:");
        jPanel1.add(lblX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        txtX1.setEditable(false);
        txtX1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(txtX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, -1));

        txtX2.setEditable(false);
        txtX2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(txtX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jTabbedPane1.addTab("Raices", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 460, 170));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 70, -1));
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 100, -1));

        setBounds(0, 0, 558, 401);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcularTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTablaActionPerformed
        try {
            this.txtResultados.setText("");
            double a = Double.parseDouble(this.txtA.getText());
            double b = Double.parseDouble(this.txtB.getText());
            double c = Double.parseDouble(this.txtC.getText());
            double xInicial = Double.parseDouble(this.txtXIncial.getText());
            double xFinal = Double.parseDouble(this.txtXFinal.getText());
            double incremento = Double.parseDouble(this.txtIncremento.getText());
            if (xInicial <= xFinal && incremento > 0) {
                for (double x = xInicial, y = 0.0; x <= xFinal; x = x + incremento) {
                    y = a * x * x + b * x + c;
                    this.txtResultados.setText(this.txtResultados.getText() + "\n\r" + x + " : " + y);
                }
            } else if (xInicial >= xFinal && incremento < 0) {
                double x = xInicial, y = 0.0;
                while (x >= xFinal) {
                    y = a * x * x + b * x + c;
                    this.txtResultados.setText(this.txtResultados.getText() + "\n\r" + x + " : " + y);

                    x = x + incremento;
                }
            } else {
                JOptionPane.showInternalMessageDialog(
                        null,
                        "El valor inicial debe ser menor que el final con incremento positivo",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showInternalMessageDialog(
                    null,
                    "El valor inicial debe ser menor que el final con incremento positivo",
                    "Error",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException exception) {
            JOptionPane.showInternalMessageDialog(
                    null,
                    "Algunos de los valores introducidos no son números",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularTablaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            double a = (Double)(this.txtA.getValue());
            double b = Double.parseDouble(this.txtB.getText());
            double c = Double.parseDouble(this.txtC.getText());
            double radicando = (b * b) - (4.0 * a * c);
            if (radicando > 0.0) {
                double x1 = (-b + Math.sqrt(radicando)) / (2.0 * a);
                double x2 = (-b - Math.sqrt(radicando)) / (2.0 * a);
                this.txtX1.setText(x1 + "");
                this.txtX2.setText(x2 + "");
            } else if (radicando == 0.0) {
                double x1 = -b / (2.0 * a);
                this.txtX1.setText(x1 + "");
                this.txtX2.setText("Solo hay una raíz");
            } else {
                double xReal = -b / (2.0 * a);
                double xImaginaria = Math.sqrt(-radicando) / (2.0 * a);
                this.txtX1.setText("" + xReal + " + " + xImaginaria + " i");
                this.txtX2.setText("" + xReal + " - " + xImaginaria + " i");
            }
        } catch (NumberFormatException exception) {
            JOptionPane.showInternalMessageDialog(
                    null,
                    "Algunos de los valores introducidos no son números",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void ingresarAlBoton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarAlBoton
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarAlBoton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaGeneralFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcularTabla;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup conversiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblX1;
    private javax.swing.JLabel lblX2;
    private javax.swing.JLabel lblXFinal;
    private javax.swing.JLabel lblXInicial;
    private javax.swing.JFormattedTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtXFinal;
    private javax.swing.JTextField txtXIncial;
    // End of variables declaration//GEN-END:variables
}
